const express = require("express");
const User = require("../models/user");
const router = express.Router();
const auth = require("../middleWares/authentication");
const { register } = require("../authControllers/register");
const login = require("../authControllers/login");
const updateUser = require("../authControllers/updateUser");
const forgotPassword = require("../authControllers/forgetPassword");
const passwordUpdate = require("../authControllers/updatePassword");
const logout = require("../authControllers/logout");
const resetPassword = require("../authControllers/resetPassword");
const getExpenses = require("../expensesControllers/getExpenses");
const getUser = require("../authControllers/userDetails");
router.post("/register", register);
router.post("/login", login);
router.post("/logout", logout);
router.put("/update", auth, updateUser);
router.put("/password/update", auth, passwordUpdate);
router.post("/password/forgot", forgotPassword);
router.put("/password/reset/:token", resetPassword);
router.get("/me", auth, getUser);

module.exports = router;
